#!/usr/bin/env python3
from flask import Flask
from flask import Response
from flask import send_file
from subprocess import run
from sys import argv
from werkzeug.serving import make_server

app = Flask(__name__)

_, input_filename, mimetype, charset = argv

def copy_to_clipboard(text: str):
    run(
        ["xclip", "-selection", "clipboard"],
        input=text.encode("utf-8"),
        check=True,
    )

@app.get("/")
def main():

    if len(charset) > 0:
        with open(input_filename, "r", encoding=charset) as f:
            content = f.read()

        # Note: The character is virtually always UTF-8, even though it gets 
        # declared as ISO-8859-1 in email.
        response = Response(
            content,
            content_type="%s; charset=%s" % (
                mimetype,
                "utf-8"
            )
        )

    else:
        response = send_file(input_filename, mimetype=mimetype)

    response.call_on_close(quit)

    return response

if __name__ == "__main__":
    schema = "http"
    hostname = "localhost"
    port = 9000

    url = "%s://%s:%d" % (schema, hostname, port)
    copy_to_clipboard(url)

    print("Open %s in a browser to see the content." % url)

    httpd = make_server("0.0.0.0", port, app)
    httpd.handle_request()

    #app.run(host="0.0.0.0", port=port)

